apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ocr-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ocr-deployment
  minReplicas: 1
  maxReplicas: 40
  targetCPUUtilizationPercentage: 50
