apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-deployment
spec:
  selector:
    matchLabels:
      app: ocr
  template:
    metadata:
      labels:
        app: ocr
    spec:
      containers:
        - name: auth
          image: otiai10/ocrserver
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: ocr-service
spec:
  selector:
    app: ocr
  ports:
    - name: ocr
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
